# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Wine and Xvfb
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y wine wine32 wget xvfb

      - name: Setup Wine environment variables
        run: |
          echo "WINEDLLOVERRIDES=mscoree,mshtml=" >> $GITHUB_ENV
          echo "DISPLAY=:99.0" >> $GITHUB_ENV
          echo "WINEDEBUG=-all" >> $GITHUB_ENV

      - name: Start Xvfb
        run: |
          Xvfb :99 -screen 0 1024x768x16 &
          sleep 2  # Give Xvfb time to start

      - name: Setup Wine Python environment
        run: |
          wget https://www.python.org/ftp/python/3.8.0/python-3.8.0-amd64.exe --no-check-certificate
          xvfb-run wine python-3.8.0-amd64.exe /quiet InstallAllUsers=1 PrependPath=1
          sleep 30  # Wait for installation to complete

      - name: Install MT5 in Wine Python
        run: |
          xvfb-run wine python -m pip install --upgrade pip
          xvfb-run wine python -m pip install MetaTrader5
          # Verify MT5 installation
          xvfb-run wine python -c "import MetaTrader5"

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel setuptools
          pip install -r requirements.txt

      - name: Create startup script
        run: |
          echo '#!/bin/bash
          export DISPLAY=:99.0
          Xvfb :99 -screen 0 1024x768x16 &
          sleep 2
          gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app' > startup.sh
          chmod +x startup.sh

      - name: Zip artifact for deployment
        run: |
          mkdir staging
          # Copy application files
          cp -r *.py *.txt startup.sh staging/
          # Copy MT5 files from Wine
          mkdir -p staging/wine_mt5
          cp -r ~/.wine/drive_c/users/*/Local\ Settings/Application\ Data/Programs/Python/Python38/Lib/site-packages/MetaTrader5 staging/wine_mt5/
          # Create the final zip
          cd staging
          zip -r ../release.zip ./*

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: |
          unzip release.zip
          rm release.zip

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'webhookpropfirm'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_65B48B30D8A747CD912945F129190EA3 }}
