# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Wine
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y wine wine32 wget

      - name: Download and Install Windows Python
        run: |
          # Download Python for Windows
          wget https://www.python.org/ftp/python/3.8.0/python-3.8.0-amd64.exe --no-check-certificate
          
          # Install Python in Wine
          wine python-3.8.0-amd64.exe /quiet InstallAllUsers=1 PrependPath=1
          sleep 30

      - name: Install MT5 in Windows Python
        run: |
          # Install MetaTrader5 in Windows Python
          wine python -m pip install --upgrade pip
          wine python -m pip install MetaTrader5

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install mt5linux

      - name: Create startup script
        run: |
          cat > startup.sh << 'EOL'
          #!/bin/bash
          
          # Start MT5 server
          python -m mt5linux "/home/site/wwwroot/.wine/drive_c/users/root/Local Settings/Application Data/Programs/Python/Python38/python.exe" &
          
          # Wait for server to start
          sleep 5
          
          # Start the application
          exec gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app --timeout 600
          EOL
          chmod +x startup.sh

      - name: Zip artifact for deployment
        run: |
          mkdir staging
          cp -r *.py *.txt startup.sh staging/
          # Copy Wine Python and MT5
          mkdir -p staging/.wine
          cp -r ~/.wine/* staging/.wine/
          cd staging
          zip -r ../release.zip ./*

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: |
          unzip release.zip

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'webhookpropfirm'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_65B48B30D8A747CD912945F129190EA3 }}
